list = ['Red', 'Green', 'Blue','Red']
print(list)
list.append('White')
print(list)
a=list.count('Red')
print(a)
b=list.index('Green')
print(b)
list.pop(0)
print(list)
list.clear()
print(list)
